#!/bin/bash

# Clone and build Anserini
git clone https://github.com/castorini/anserini.git && cd anserini
mvn clean package appassembler:assemble -DskipTests

# Modify ES and Kibana config
printf '\ntransport.host: localhost\ntransport.tcp.port: 9300\nhttp.port: 9200\nnetwork.host: 0.0.0.0\n' >> /etc/elasticsearch/elasticsearch.yml
printf '\nserver.host: 0.0.0.0\n' >> /etc/kibana/kibana.yml

# Start ELK
service elasticsearch start
service logstash start
service kibana start
